apiVersion: cloudbuild.googleapis.com/v1
kind: BuildTrigger
metadata:
  name: auto-deploy-fmplace-recommender
description: Deploy FMPlace recommender with proper logging
triggerTemplate:
  repoName: fmplace-recommender
  branchName: "^main$"
  projectId: fmplace-api
build:
  source:
    repoSource:
      projectId: fmplace-api
      repoName: fmplace-recommender
      branchName: main
  steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/fmplace-api/fmplace-recommender', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/fmplace-api/fmplace-recommender']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'fmplace-recommender',
             '--image', 'gcr.io/fmplace-api/fmplace-recommender',
             '--region', 'europe-west1',
             '--platform', 'managed',
             '--allow-unauthenticated']
  options:
    logging: CLOUD_LOGGING_ONLY
