name: Generate JSON from Excel

# Dispara al hacer push en estos archivos o manualmente desde GitHub UI
on:
  push:
    paths:
      - 'config_recomendador.xlsx'            # tu Excel
      - 'excel_to_json.py'                    # el script
      - '.github/workflows/generate-json.yml' # el propio workflow
      - 'adjustments.json'                    # si lo tienes
  workflow_dispatch:                          # para lanzar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # necesitamos todo el historial para hacer commit+push
          fetch-depth: 0
          # usar GITHUB_TOKEN para push
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Generate JSON
        run: python excel_to_json.py

      - name: Commit JSON files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # forzamos el add de los JSON aunque estén en .gitignore
          git add -f metadata.json scores.json weights.json justifications.json adjustments.json || true
          git commit -m "ci: update JSON configs from Excel" || echo "No changes to commit"
          git push


