# .github/workflows/generate-json.yml
name: Generate JSON from Excel

on:
  push:
    paths:
      - 'config_recomendador.xlsx'
      - 'excel_to_json.py'
      - '.github/workflows/generate-json.yml'
      - 'adjustments.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Generate JSON
        run: python excel_to_json.py

      - name: Commit JSON files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f metadata.json scores.json weights.json justifications.json adjustments.json
          git commit -m "Update JSON configs from Excel" || echo "No changes to commit"
          git push

